### ISSUE TITLE
Make URL and Domain classes

### ISSUE THREAD

**Issue by randomwalker** [dreisman/WebCensusNotebook#1]
The backend has a lot of intelligence about what a URL "means", and the best way to expose this to the user is to encapsulate it in a class. For example, a URL object could expose the parsed parameters. It could even reveal if it corresponds to a cookie sync call, RTB, or some other tracking technique.

Should we write this class from scratch or subclass some existing URL library? At first the latter sounds obvious, but typically URL libs are about making HTTP requests, which is irrelevant in our context.

Domain could be a separate class or a subclass of URL. A Domain object would be the way to look up Alexa category, the organization that owns it, and stuff like that.

**Comment by dreisman** [comment]
Current arrangement:
-FirstParty
-ThirdParty
-Organization
-URI (instance of a resource)

Closing this bug for now. If we continue to think of other useful abstractions, we'll come up with them then.
